import type { ToolbeltAction, Seed } from './types/types'
import { gardeningShears, wateringCan, seedBag } from '@/assets/overlay'
import { bonsaiSeed, cactusSeed, daisySeed, lavenderSeed, roseSeed, sunflowerSeed, tulipSeed } from '@/assets/seeds'

export const toolbeltActions: ToolbeltAction[] = [
    {
        name: 'plant-seed',
        label: 'Seed Bag',
        icon: seedBag,
    },
    {
        name: 'harvest-plant',
        label: 'Gardening Shears',
        icon: gardeningShears,
    },
    {
        name: 'water-plant',
        label: 'Watering Can',
        icon: wateringCan,
    },
]

export const seedPrice = 10

export const seeds: Seed[] = [
    {
        name: 'bonsai',
        label: 'Bonsai Seed',
        icon: bonsaiSeed,
        count: 3,
        description: 'A miniature tree cultivated for patience and precision. Grows slowly but adds elegance to any garden.',
        category: ['ornamental', 'tree'],
        growTime: 4,
        phases: 4,
        maxWateringSkips: 2,
        rarity: 'common',
        sellPrice: 15,
        buyPrice: seedPrice,
        unlockPrice: 50,
        locked: false,
    },
    {
        name: 'cactus',
        label: 'Cactus Seed',
        icon: cactusSeed,
        count: 3,
        description: 'A resilient desert plant that thrives with minimal water. Great for low-maintenance gardening.',
        category: ['succulent', 'desert'],
        growTime: 4,
        phases: 4,
        maxWateringSkips: 2,
        rarity: 'common',
        sellPrice: 15,
        buyPrice: seedPrice,
        unlockPrice: 50,
        locked: false,
    },
    {
        name: 'daisy',
        label: 'Daisy Seed',
        icon: daisySeed,
        count: 3,
        description: 'A cheerful white flower with a sunny center. Symbol of innocence and fresh starts.',
        category: ['flower', 'wildflower'],
        growTime: 4,
        phases: 4,
        maxWateringSkips: 2,
        rarity: 'common',
        sellPrice: 15,
        buyPrice: seedPrice,
        unlockPrice: 50,
        locked: false,
    },
    {
        name: 'lavender',
        label: 'Lavender Seed',
        icon: lavenderSeed,
        count: 0,
        description: 'A fragrant herb known for its calming scent and beautiful purple blooms.',
        category: ['flower', 'herb'],
        growTime: 4,
        phases: 4,
        maxWateringSkips: 2,
        rarity: 'common',
        sellPrice: 15,
        buyPrice: seedPrice,
        unlockPrice: 5,
        locked: true,
    },
    {
        name: 'rose',
        label: 'Rose Seed',
        icon: roseSeed,
        count: 0,
        description: 'A romantic flower with delicate petals and thorns. A timeless symbol of love and beauty.',
        category: ['flower', 'ornamental'],
        growTime: 4,
        phases: 4,
        maxWateringSkips: 2,
        rarity: 'common',
        sellPrice: 15,
        buyPrice: seedPrice,
        unlockPrice: 50,
        locked: true,
    },
    {
        name: 'sunflower',
        label: 'Sunflower Seed',
        icon: sunflowerSeed,
        count: 0,
        description: 'A tall, sun-loving plant that always faces the light. Produces seeds and brightens any space.',
        category: ['flower', 'edible'],
        growTime: 4,
        phases: 4,
        maxWateringSkips: 2,
        rarity: 'common',
        sellPrice: 15,
        buyPrice: seedPrice,
        unlockPrice: 50,
        locked: true,
    },
    {
        name: 'tulip',
        label: 'Tulip Seed',
        icon: tulipSeed,
        count: 0,
        description: 'A spring-blooming bulb with smooth, cup-shaped petals in vibrant colors.',
        category: ['flower', 'ornamental'],
        growTime: 4,
        phases: 4,
        maxWateringSkips: 2,
        rarity: 'common',
        sellPrice: 15,
        buyPrice: seedPrice,
        unlockPrice: 50,
        locked: true,
    },
]

export const seedIcons: Record<string, string> = {
    bonsai: bonsaiSeed,
    cactus: cactusSeed,
    daisy: daisySeed,
    lavender: lavenderSeed,
    rose: roseSeed,
    sunflower: sunflowerSeed,
    tulip: tulipSeed,
}
export const STARTING_BALANCE = seedPrice * 6
// Testing
// export const STARTING_BALANCE = seedPrice * 100
